trigger:  
- feature/*
- main

pool: Default

# variables:
#   - group: monolethic_infra 

stages:
- stage: Build
  displayName: Build
  jobs:       
  - job: TerraformInitPlan
    displayName: Terraform Init and Plan Job
    steps: 
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/envirionments/dev'
        backendServiceArm: 'vinitk11'
        backendAzureRmOverrideSubscriptionID: 'b37d1b55-e5e8-4acb-a848-fd89484f0997'
        backendAzureRmResourceGroupName: 'mira'
        backendAzureRmStorageAccountName: 'ancient11'
        backendAzureRmContainerName: 'era'
        backendAzureRmKey: 'dev.terraform.tfstate'
    

    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: 'envirionments/dev'
        environmentServiceNameAzureRM: 'vinitk11'

- stage: Scanning
  displayName: Scanning
  jobs: 
  - job: TFSecScanningJob
    displayName: TFSEC Scanning Wala Job
    pool: Default
    steps:
    - task: tfsec@1
      inputs:
        version: 'v1.26.0'
        dir: 'envirionments/dev'

  - job: TfLintScanningJob
    displayName: TFLINT Scanning Wala Job
    pool: Default
    steps:
    - task: CmdLine@2
      inputs:
        script: 'echo Hello world'

- stage: Deploy
  displayName: Deploy
  condition: succeeded()
  # condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
  jobs: 
  - job: ManualValidation
    displayName: Manual Validation kardo Please
    pool: server
    steps:
    # - task: ManualValidation@1
    #   inputs:
    #     notifyUsers: 'shivamprajapati1633@gmail.com'
    #     approvers: 'shivamprajapati1633@gmail.com'
    #     instructions: 'Plan check kardo...'

    - task: ManualValidation@1
      inputs:
       instructions: 'Plan check karlo. Approve karne ke liye Resume button dabao.'
       onTimeout: 'reject'
       timeout: '0'
       approvers: ''
       notifyUsers: ''


  - job: TerraformApply
    displayName: Terraform Apply wala Job
    dependsOn: ManualValidation
    pool: Default
    steps:
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/envirionments/dev'
        backendServiceArm: 'vinitk11'
        backendAzureRmOverrideSubscriptionID: 'b37d1b55-e5e8-4acb-a848-fd89484f0997'
        backendAzureRmResourceGroupName: 'mira'
        backendAzureRmStorageAccountName: 'ancient11'
        backendAzureRmContainerName: 'era'
        backendAzureRmKey: 'dev.terraform.tfstate'

    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: 'environments/dev'
        environmentServiceNameAzureRM: 'vinitk11'